# Generated by Django 4.1.7 on 2023-05-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
